ALTER TABLE delivery ALTER COLUMN status VARCHAR(20);
UPDATE delivery SET status = 'SHIPPED' WHERE CAST(status AS VARCHAR) = 'COMP';
ALTER TABLE IF EXISTS customer_return ALTER COLUMN status VARCHAR(30);
