package com.jhg.hgpage.realtime.outbox;

public enum NotificationEventType {
    PAYMENT_APPROVED,
    PAYMENT_FAILED,
    PAYMENT_REVIEW_REQUIRED,
    ORDER_BACKORDERED,
    STOCK_ALLOCATED,
    ORDER_CANCELLED,
    SHIPMENT_STARTED,
    DELIVERY_COMPLETED,
    RETURN_REQUESTED,
    RETURN_REJECTED,
    RETURN_RECEIVED,
    RETURN_COMPLETED,
    RETURN_CANCELLED,
    REFUND_COMPLETED,
    REFUND_REVIEW_REQUIRED
}
